### ISSUE TITLE
Issues with the sockets

### ISSUE THREAD

**Issue by crblanaru** [QuantumObject/docker-zoneminder#11]
Dear package maintainer, 

I have tried everything regarding this issue online. Everything seems to be correct, but I cannot see any stream irrespective of my configuration. This happens with the default installation:

2015-11-17 19:51:33.864138	web_php	129	ERR	socket_sendto( /var/run/zm/zms-923183s.sock ) failed: No such file or directory	/usr/share/zoneminder/www/includes/functions.php	2347
2015-11-17 19:51:30.859287	web_js	133	ERR	getStreamCmdResponse stream error: socket_sendto( /var/run/zm/zms-923183s.sock ) failed: No such file or directory - checkStreamForErrors()	?view=watch	
2015-11-17 19:51:30.779953	web_php	128	ERR	socket_sendto( /var/run/zm/zms-923183s.sock ) failed: No such file or directory	/usr/share/zoneminder/www/includes/functions.php	2347

docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

I am running the container on a updated Ubuntu 14.04 machine.

Do you happen to know what could be causing this?

Kind regards,
Cristian

**Comment by angelrr7702** [comment]
That because I update to last version and they change some stuff a the PPA to be more compatible for debian/ubuntu .. but brake everything else at the same time I was unable to build at docker repository because of the two days ..the service was down .. for trusted build .. I will check again today and I will try to fix it .

sincerely
Angel Rodriguez

**Comment by angelrr7702** [comment]
Hi,
 I still unable to fix it. it work fine before but after some update fail from 1.28.1 (worked fine) to 1.28.108 and now 1.28.109 it fail .. I didn't find any info at forum that help with this problem .

**Comment by crblanaru** [comment]
I have to admit that I have tried most things that I could find on forums and I was also unlucky.

It seems that configuration is correct, but still, it will not create the sockets. 

Many Thanks,
- Cristian Blanaru

**Comment by angelrr7702** [comment]
Relate to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=666980

and 

https://forums.zoneminder.com/viewtopic.php?f=29&t=19657&p=76785&hilit=AUTH_RELAY#p76785


it work fine if you don't used authentication , I still looking for a solution.

**Comment by angelrr7702** [comment]
For live view via the web UI to work, you need to edit config -> paths, and change:

"/cgi-bin/nph-zms" to "/zm/cgi-bin/nph-zms"

and if you change System=> "Authenticate user logins to ZoneMinder" you at this moment need to change "Method used to relay authentication information " to "None" if this not done you will be unable to see live view. This only recommended if you are using https to protect password(This relate to a misconfiguration or problem with this container still trying to find a better solutions).

**Comment by angelrr7702** [comment]
I add yesterday the --shm-size=4096m options when executing docket run , in that way you don't need to used --privileged=true (this only work for new docker 1.10) . About the webui before I have a lot of problem to make it work  (relate to sockets error) , appear that there are different reason it fail :

1)
need to edit config -> paths, and change:
"/cgi-bin/nph-zms" to: "/zm/cgi-bin/nph-zms"

2) fix timezone at php.ini ==> right now my container have America/New York before no was define and create failure on webui

3) if you change to authentication required to login OPT_USE_AUTH them webui fail if you don't change AUTH_RELAY from "hashed" to "none" and this make your site less secure for that reason I deploy under https (letsencrypt ) . still need to find a way for fix it .

for that reason I deploy under https (letsencrypt ) ==>this no part of container but using 
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion
and 
http://jasonwilder.com/blog/2014/03/25/automated-nginx-reverse-proxy-for-docker/

there was for some people the need to mount -v /etc/localtime:/etc/localtime:ro to get correct system time when the problem is more relate to point 2. 

sincerely
Angel Rodriguez
