### ISSUE TITLE
Filter Creation Broken with current ZM code

### ISSUE THREAD

**Issue by forkineye** [QuantumObject/docker-zoneminder#67]
The ZM code in the current docker image has broken filter creation as referenced here - https://github.com/ZoneMinder/zoneminder/issues/2498 and fixed with this merged PR - https://github.com/ZoneMinder/zoneminder/pull/2438. Could we get an updated docker image with these changes? Thanks!

**Comment by forkineye** [comment]
Fixed with the latest docker image, thanks!

**Comment by forkineye** [comment]
Closed too soon. I'm able to edit filters, but not create them.

**Comment by angelrr7702** [comment]
please check again move from dev version to more stable version 1.32.3 , let me know if problem continue ..

**Comment by phillijw** [comment]
This somehow took me back from 1.33 to 1.32 and everything is broken now (I was also having the filter issue which is why I upgraded). Can we please try to not use the "latest" tag for docker? It would be far clearer to use actual versions. I believe I may have lost a lot of data if I'm not able to sort out the issue I had.

**Comment by Gehilfe** [comment]
The update to version 1.33.2 also destroyed my ZoneMinder installation. I'm using version 1.33.1 again with the merged PR

**Comment by phillijw** [comment]
if you change the Dockerfile and point it back to 'master' rather than 1.32, then build the image locally and then using the new image, it will take you back to the proper code as an interim solution
