### ISSUE TITLE
Accessing via domain name instead of IP?

### ISSUE THREAD

**Issue by defaye** [QuantumObject/docker-zoneminder#9]
Do you have any easy solution to setting up with a domain so that you can view the stream via example.com/zm instead of by IP address/zm? The stream doesn't work when accessed over the domain but over IP it does. (By doesn't work - I mean only the stream). I used a reverse proxy to forward the container on 8080 to 80.

**Comment by angelrr7702** [comment]
Sorry I unable to help you at the moment ,,, if you find solution a this problem let me know ...  problem with proxy is one of the problem with more that one of my containers .. some web application that install and work fine over ubuntu when I move to container it show this problems .. or others ..  relate to domain or internal ip and external ip ..

**Comment by angelrr7702** [comment]
The container already work on port 80 don't need to reverse proxy for it 

 - p 80:80 will work at docker run command.  and I have a container running zoneminder using a domain name ...  http://www.quantumobject.com:49153/zm/  in this case I use -p 49153:80 because i already have port 80 and 8080 in used for another container at the same domain ..
